[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
serverAddress = "localhost"

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E8F5E9"
textColor = "#212121"
font = "sans serif"
